global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#ivan_gorban'
