version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  ui:
    # build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - 9292:${REDDIT_PORT}/tcp
    networks:
      - reddit
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  post:
    # build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - reddit
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  comment:
    # build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - reddit
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

volumes:
  post_db:

networks:
  reddit:
