kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: si6YO6k5fh7EacrqtZt5R48EwX4yZVjn7oZJyU1tpeA=
      - identity: {}
