version: '3.3'
services:
  ui:
    command: ["puma", "--debug", "-w", "2"]
    volumes:
      - ui:/app:rw
  post:
    volumes:
      - post:/app:rw
  comment:
    volumes:
      - comment:/app:rw

volumes:
  ui:
  post:
  comment:
